version: '3.7'
services:
  client:
    container_name: flutter_client
    restart: always
    build: ./web
    ports:
      - '4443:443'
      #- '80:443'
    links:
      - server
  server:
    container_name: node_server
    restart: always
    build: ./backend
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: database
    image: mongo
    ports:
      - '27017:27017'